### ISSUE TITLE
Can you Deploy to services like Netlify, Heroku, etc. and/or cPanel?

### ISSUE THREAD

**Issue by ShreyaanVashishtha** [google/nomulus#1071]
Is it possible to deploy Nomulus on CDNs like Netlify and Heroku and/or on cPanel shared hosting?

Thanks

**Comment by mindhog** [comment]
At this time, the Nomulus back-end runs only on Google App Engine.  Our goal is to port it to Kubernetes, at which point it should run on any cloud provider that supports Kubernetes, although there will still be some GCP dependencies (e.g. Cloud SQL).

**Comment by ShreyaanVashishtha** [comment]
Ok, So I can’t run iy on any cloud provider just yet? Am I right?

**Comment by mindhog** [comment]
As stated earlier, you can only run it on Google App Engine.

**Comment by ShreyaanVashishtha** [comment]
Ok Thanks
