### ISSUE TITLE
max_instances is set to 100 for the backend service

### ISSUE THREAD

**Issue by reesericci** [google/nomulus#1238]
how do i change this so it deploys properly?

**Comment by CydeWeys** [comment]
You need to update the `appengine-web.xml` file for the `backend` service for whichever environment you're attempting to deploy.  E.g. here's the file for production: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/backend/WEB-INF/appengine-web.xml;l=10

For more general documentation on `appengine-web.xml`, see: https://cloud.google.com/appengine/docs/standard/java/config/appref

**Comment by reesericci** [comment]
i've moved on from nomulus.

**Comment by pangwangshu** [comment]
Can we change it to 25 so people won't get error on deployment?

**Comment by mindhog** [comment]
As a general rule, we expect users of the system to [modify configuration appropriately prior to deployment.](https://cs.opensource.google/nomulus/nomulus/+/master:docs/configuration.md), so we're not likely to change this.

That said, we don't have this particular issue documented, so I've created #1639 to add a note on this.

**Comment by saltyfishyjk** [comment]
> You need to update the `appengine-web.xml` file for the `backend` service for whichever environment you're attempting to deploy. E.g. here's the file for production: https://cs.opensource.google/nomulus/nomulus/+/master:core/src/main/java/google/registry/env/production/backend/WEB-INF/appengine-web.xml;l=10
> 
> For more general documentation on `appengine-web.xml`, see: https://cloud.google.com/appengine/docs/standard/java/config/appref

Hello,
I encountered the same issue and tried setting a lower number of max_instances in every appengine-web.xml of backend and bsa (such as `./core/build/resources/main/google/registry/env/sandbox/backend/WEB-INF/appengine-web.xml` and `./core/build/resources/main/google/registry/env/alpha/backend/WEB-INF/appengine-web.xml`), but it didn't work. Here is my post on the Nomulus Google Group: [Nomulus Google Group post](https://groups.google.com/g/nomulus-discuss/c/2WWIoQJnyoA/m/syMqRCscAQAJ). I would greatly appreciate any help you can provide with this problem.
Thank you.
