### ISSUE TITLE
Facing problem for task ":core:fragileTest" as Execution is Failed

### ISSUE THREAD

**Issue by piyu8233** [google/nomulus#1767]
Plugins: Using default repo...

> Configure project :buildSrc
enableDependencyLocking is true
Java dependencies: Using Maven central...

> Configure project :
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...
Java dependencies: Using Maven Central...

> Task :getBuildSrcDeps_499323d9-ed30-4770-96cb-0b339515e85f

> Configure project :
enableDependencyLocking is true
Java dependencies: Using Maven central...

> Task :exportDependencies
dependency is configuration ':annotationProcessor'
dependency is configuration ':apiElements'
dependency is configuration ':archives'
dependency is configuration ':checkstyle'
dependency is configuration ':compileClasspath'
dependency is configuration ':compileOnly'
dependency is configuration ':default'
dependency is configuration ':deploy_jar'
dependency is configuration ':errorprone'
dependency is configuration ':errorproneJavac'
dependency is configuration ':implementation'
dependency is configuration ':jacocoAgent'
dependency is configuration ':jacocoAnt'
dependency is configuration ':runtimeClasspath'
dependency is configuration ':runtimeElements'
dependency is configuration ':runtimeOnly'
dependency is configuration ':testAnnotationProcessor'
dependency is configuration ':testCompileClasspath'
dependency is configuration ':testCompileOnly'
dependency is configuration ':testImplementation'
dependency is configuration ':testRuntimeClasspath'
dependency is configuration ':testRuntimeOnly'

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

> Task :checkBuildSrcLicense

> Configure project :
enableDependencyLocking is true
Java dependencies: Using Maven central...

> Task :checkLicensePreparation
> Task :generateLicenseReport
> Task :checkLicense

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
3 actionable tasks: 3 executed

> Task :javaIncrementalFormatCheck
JAVA_HOME=null
PATH=/home/ubuntu/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
java is /usr/bin/java
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu118.04, mixed mode, sharing)

Incremental Java format check ok.

> Task :npmSetup

added 1 package, and audited 436 packages in 8s

3 packages are looking for funding
  run `npm fund` for details

14 vulnerabilities (7 moderate, 4 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> Task :npmInstall
added 1 package from 24 contributors and audited 1 package in 0.666s
found 0 vulnerabilities

> Task :core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :runPresubmits
python version is 3.10.6 (main, Aug  2 2022, 15:11:03) [GCC 7.5.0]

> Task :services:backend:appengineStage
Reading application configuration data...
2022-08-31 09:21:15.662:INFO::main: Logging initialized @310ms to org.eclipse.jetty.util.log.StdErrLog

Beginning interaction for module backend...
0% Scanning for jsp files.
0% Generated git repository information file.
Success.
Temporary staging for module backend directory left in /root/nomulus/services/backend/build/staged-app

> Task :services:default:appengineStage
Reading application configuration data...
2022-08-31 09:21:36.239:INFO::main: Logging initialized @325ms to org.eclipse.jetty.util.log.StdErrLog
Aug 31, 2022 9:21:36 AM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
INFO: Successfully processed /root/nomulus/services/default/build/exploded-default/WEB-INF/datastore-indexes.xml

Beginning interaction for module default...
0% Scanning for jsp files.
0% Generated git repository information file.
Success.
Temporary staging for module default directory left in /root/nomulus/services/default/build/staged-app

> Task :services:pubapi:appengineStage
Reading application configuration data...
2022-08-31 09:21:57.371:INFO::main: Logging initialized @271ms to org.eclipse.jetty.util.log.StdErrLog

Beginning interaction for module pubapi...
0% Scanning for jsp files.
0% Generated git repository information file.
Success.
Temporary staging for module pubapi directory left in /root/nomulus/services/pubapi/build/staged-app

> Task :services:tools:appengineStage
Reading application configuration data...
2022-08-31 09:22:17.533:INFO::main: Logging initialized @223ms to org.eclipse.jetty.util.log.StdErrLog

Beginning interaction for module tools...
0% Scanning for jsp files.
0% Generated git repository information file.
Success.
Temporary staging for module tools directory left in /root/nomulus/services/tools/build/staged-app

> Task :core:buildToolImage
Sending build context to Docker daemon  290.7MB

Step 1/3 : FROM gcr.io/distroless/java:debug
 ---> 79d4d461ea6f
Step 2/3 : ADD build/libs/nomulus.jar /nomulus.jar
 ---> bf6b61994bb7
Step 3/3 : ENTRYPOINT ["/usr/bin/java", "-jar", "/nomulus.jar"]
 ---> Running in 73ef34983733
Removing intermediate container 73ef34983733
 ---> 4a9597e3bed2
Successfully built 4a9597e3bed2
Successfully tagged nomulus-tool:latest

> Task :core:fragileTest
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

PathParameterTest > testOutputFileValidate_notWritable_throws() **FAILED**
    org.opentest4j.AssertionFailedError at PathParameterTest.java:146

PathParameterTest > testInputFileValidate_unreadableFile_throws() **FAILED**
    org.opentest4j.AssertionFailedError at PathParameterTest.java:109
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

RegistrarConsoleScreenshotTest > settingsContact_asAdmin() > google.registry.webdriver.RegistrarConsoleScreenshotTest.settingsContact_asAdmin()[3] **FAILED**
    org.opentest4j.AssertionFailedError at RetryingTestExtension.java:147
        Caused by: java.util.concurrent.TimeoutException at TimeoutExceptionFactory.java:29

RegistrarConsoleScreenshotTest > settingsContactEdit_setRegistryLockPassword() > google.registry.webdriver.RegistrarConsoleScreenshotTest.settingsContactEdit_setRegistryLockPassword()[3] **FAILED**
    org.opentest4j.AssertionFailedError at RetryingTestExtension.java:147
        Caused by: java.util.concurrent.TimeoutException at TimeoutExceptionFactory.java:29

RegistrarConsoleScreenshotTest > getOteStatus_completed() > google.registry.webdriver.RegistrarConsoleScreenshotTest.getOteStatus_completed()[3] **FAILED**
    org.opentest4j.AssertionFailedError at RetryingTestExtension.java:147
        Caused by: java.util.concurrent.TimeoutException at TimeoutExceptionFactory.java:29

RegistrarConsoleScreenshotTest > settingsContactAdd() > google.registry.webdriver.RegistrarConsoleScreenshotTest.settingsContactAdd()[3] **FAILED**
    org.opentest4j.AssertionFailedError at RetryingTestExtension.java:147
        Caused by: java.util.concurrent.TimeoutException at TimeoutExceptionFactory.java:29
<======-------> 46% EXECUTING [36m 31s]
> :core:fragileTest > 59 tests completed, 6 failed, 9 skipped
> :core:fragileTest > Executing test google.registry.webdriver.RegistrarConsoleScreenshotTest

**Comment by UTKARSH8768** [comment]
hey i am utkarsh sharma can you please assign me a task to contribute in your project. This is for my open source project lab in my college. contact me at my mail id sharmautkarsh19@siesgst.ac.in.

**Comment by piyu8233** [comment]
Hi Utkarsh,
How can i help you in this?? Please tell
You may also contact with me over my mail id p.agg1995@gmail.com
