### ISSUE TITLE
Issue Templates ⚠

### ISSUE THREAD

**Issue by ItsRoy69** [google/nomulus#1859]
### Issue Templates are awesome to have

- Since there are alot of folks contributing to this Opensource project i would suggest we have ISSUE TEMPLATES
- That way we can categorize the issues more and manage it more decently.
- I can work on this if I am being assigned

![image](https://user-images.githubusercontent.com/78967360/204188883-d951de2a-ecda-4b22-aba5-a17e50691711.png)

Here's how the forms looks :
![image](https://user-images.githubusercontent.com/78967360/204188916-6a00eacb-219c-4504-840d-e9eb42a09789.png)

**Comment by Mythical1008** [comment]
can i work on it?
