### ISSUE TITLE
I found a typo bug in the provided Markdown file. In the section "Build the tool," there is an incorrect path mentioned for aliasing the compiled binary.

### ISSUE THREAD

**Issue by champ96k** [google/nomulus#2041]
I found a typo bug in the provided Markdown file. In the section "Build the tool," there is an incorrect path mentioned for aliasing the compiled binary. The correct path should be `bazel-bin/java/google/registry/tools/nomulus` instead of `bazel-genfiles/java/google/registry/nomulus`. Here's the corrected sentence:

It's recommended that you alias the compiled binary located at `bazel-bin/java/google/registry/tools/nomulus` (or add it to your shell path) so that you can run it easily.

**Comment by Oxzoid** [comment]
it is already fixed
![image](https://github.com/google/nomulus/assets/35035937/e586ae07-dedc-41d4-917f-d51a4a8f7429)

**Comment by champ96k** [comment]
Closing this issue, It’s already fixed!
