### ISSUE TITLE
Encountered 'sed: 1: "/private/var/tmp/_bazel ...": invalid command code v' while building codebase

### ISSUE THREAD

**Issue by revprez** [google/nomulus#67]
## Overview

Encountering error apparently related to `sed` while attempting to build the code base. Not familiar with bazel or xjc well enough to diagnose further.

## System information

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12.5
BuildVersion:   16F73
```

## Nomulus information

Building from current HEAD.

```
$ git rev-parse HEAD
dce0daafc38a845879b5f5a9082754c219d406ec
```

## Steps to take to reproduce
```
$ git clone https://github.com/google/nomulus.git
$ pushd nomulus
$ bazel --batch build //java{,tests}/google/registry/...
```

## Expected result

From the [installation instructions](https://github.com/google/nomulus/blob/master/docs/install.md):

```
INFO: Found 584 targets...
[ .. snip .. ]
INFO: Elapsed time: 124.433s, Critical Path: 116.92s
```

## Actual result

```
Extracting Bazel installation...
INFO: Found 629 targets...
ERROR: /Users/revprez/dev/scm/git/encirca/orchestration/core/encirca/projects/nomulus/java/google/registry/xjc/BUILD:31:1: Executing genrule //java/google/registry/xjc:jaxb_srcs failed: Process exited with status 1 [sandboxed].
sed: 1: "/private/var/tmp/_bazel ...": invalid command code v
Use --strategy=Genrule=standalone to disable sandboxing for the failing actions.
INFO: Elapsed time: 66.546s, Critical Path: 13.98s
```

**Comment by CydeWeys** [comment]
This appears to be an issue related to OS X: https://stackoverflow.com/questions/19456518/invalid-command-code-despite-escaping-periods-using-sed

Try compiling using Linux.  We don't use OS X and thus can't support it. If you don't already have a Linux instance available somewhere, you can easily spin up a new one in Google Compute Engine.

**Comment by revprez** [comment]
@CydeWeys : I'll give it a shot. Closing as OS X is an unsupported platform.

**Comment by jianglai** [comment]
@revprez can you give it a try again? We pushed a fix that should allow you to build on macOS.

**Comment by revprez** [comment]
@jianglai : I'll give it a shot this evening.
