### ISSUE TITLE
Creating a TLD?

### ISSUE THREAD

**Issue by atonb117** [google/nomulus#69]
Can I spin this up and actually create a private TLD that doesn't currently exist, like .nyame or .kofi, while managing it myself?

I trying to understand the implications behind this technology.

**Comment by CydeWeys** [comment]
You sure can, however, it will not resolve on the global Internet. You'd
run your own DNS, populated from Nomulus, and then set up your other
computers to use that DNS server.

However, unless you plan on emulating private registrars too, it's simpler
to just skip straight to running your own DNS which you populate manually.

**Comment by nolliug** [comment]
Hello, you need to wait for the next ICANN new gTLD application round to create an official TLD. This should be open within a few years period of time. I do a follow up with news on the subject here: http://www.gtld.club/p/newsletter.html

**Comment by dnsguru** [comment]
_IF_ you create test TLD(s), use .example - or you might be safe to prefix
the TLDs that you're testing with xx-- so as to avoid contributing to
namespace collision.  Alternatively, create 'TLDs' as subdomains of
existing domain names (ie if you own bar.foo, create TLD.bar.foo as your
"TLD")

Jothan Frakes
+1.206-355-0230 tel
+1.206-201-6881 fax

**Comment by atonb117** [comment]
Will do @dnsguru. 

Excellent resource, @nolliug; subscribing.

Great insights, @CydeWeys.  When you say "resolve", that means others couldn't simply type the address in their brower's address bar?  If not, how can they get the TLD that's been created?

**Comment by jianglai** [comment]
ICANN will need to delegate the TLD created to your designated nameservers for it to resolve. You can create a whole hierarchy of domain names that mimics the internet itself, but unless the root nameservers actually point to it, it is isolated from the internet that everyone uses.

As @nolliug pointed out, when ICANN does the next round of gTLD expansion, newly created TLDs will be delegated.

Note that Nomulus supports multi-part TLDs, so if you do own domains like bar.foo, you can use Nomulus to manage subdomains under it. But I agree with @CydeWeys that it is probably easier to just maintain the DNS yourself. The main purpose of Nomulus is to manage EPP communications between registries and registrars. If bar.foo is not open for registration, there's no point running a full registry platform like Nomulus.

**Comment by CydeWeys** [comment]
It's important to point out that there's a long elaborate process involved in getting a TLD delegated to you, as well as a startup cost of something on the order of $200K (if no one else wants that TLD) plus $25K per year, all paid to ICANN.  So how badly do you want .nyame or .kofi?

**Comment by atonb117** [comment]
@jianglai and @CydeWeys, can you quickly explain what you mean by "running/maintaining the DNS yourself"?

**Comment by CydeWeys** [comment]
There's a large variety of software applications that can be used to run DNS, with BIND being the most well known.  You can run your own DNS using this software, then configure your other computers to use it.  Then you'll be able to do whatever you want with domain name resolution.

**Comment by atonb117** [comment]
Got it @CydeWeys.  Thanks!
