### ISSUE TITLE
Any chance to move zip_file() rule to a standalone repository?

### ISSUE THREAD

**Issue by VictoriaRaymond** [google/nomulus#83]
The [zip_file()](https://github.com/google/nomulus/blob/master/java/google/registry/builddefs/zip_file.bzl) rule is extremely useful for releasing packages, and there is high demand for that. See https://github.com/bazelbuild/bazel/issues/3768, https://github.com/bazelbuild/bazel/issues/2336, and  [discussions](https://groups.google.com/forum/#!topic/bazel-discuss/vuNtY99tGDU).

I'd like to use this rule in my project, but don't want to depend on the whole nomulus repository. It would be great that the rule is moved to a standalone repo.

**Comment by aiuto** [comment]
The best place to put a zip rule would now be http://github.com/bazelbuild/rules_pkg.
