### ISSUE TITLE
Platform agnostic deployment?

### ISSUE THREAD

**Issue by hschoenburg** [google/nomulus#86]
Hello Nomulus,

Please accept my apologies for using Issues to ask a questio.

I am seeking to use nomulus to manage an experimental TLD on Handshake. 

Can I deploy nomulus on my own independent server without Google App Engine? Or is it configured to connect to a proprietary Google datastore?

Does nomulus require me to register with GSuite as well? I'm unclear on how coupled nomulus is with Google services.

Thank you.

**Comment by nolliug** [comment]
I am interested in anyone creating an offer, based on Nomulus, to host a new gTLD. I was informed that Google won't be developing a solution for future applicants from the next round but...someone else might.
